In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
Train = pd.read_csv('kc_house_train_data.csv')
Test = pd.read_csv('kc_house_test_data.csv')
sales = pd.read_csv('kc_house_data.csv')
sales.head()
X = sales.iloc[:,5]
X = X[:,np.newaxis]
y = sales.iloc[:,2] 
y = y[:,np.newaxis]
X_train = Train.iloc[:,5]
X_train = X_train[:,np.newaxis]
X_test = Test.iloc[:,5]
X_test = X_test[:,np.newaxis]
y_train = Train.iloc[:,2]
y_train = y_train[:,np.newaxis]
y_test = Test.iloc[:,2]
y_test = y_test[:,np.newaxis]

In [65]:
sales.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)

In [69]:
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_train, y_train)

reg.coef_

reg.intercept_

predict =reg.predict(X_test)
TrainPred = reg.predict(X_train)

In [70]:
reg.coef_

array([[281.95883963]])

In [71]:
reg.intercept_

array([-47116.07907289])

In [72]:
reg.predict(np.array([[2650]]))

array([[700074.84594751]])

In [73]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, predict)

65122471888.81819

In [74]:
mean_squared_error(y_train, TrainPred)

69139343889.62743

In [75]:
RSStrain = sum((y_train - TrainPred)**2)

In [76]:
RSStrain

array([1.20191835e+15])

In [77]:
RSStest = sum((y_test - predict)**2)

In [78]:
RSStest

array([2.75402934e+14])

In [79]:
reg2 = LinearRegression().fit(X_train, y_train)
reg2.score(X_train, y_train)

reg2.coef_

reg2.intercept_

predict =reg.predict(X_test)
TrainPred = reg.predict(X_train)

In [80]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [81]:
slope = 280.76
inter = -44850
var = 0.092903
inter*var


-4166.69955

# Week2 exercise

In [7]:
BedroomSq= Test['bedrooms']**2

In [8]:
BedroomSq.mean()

12.4466777015843

In [9]:
Bedbath =Test['bedrooms']*Test['bathrooms']

In [11]:
Bedbath.mean()

7.5039016315913925

In [12]:
latlon = Test['lat']+Test['long']

In [14]:
latlon.mean()
import scipy

-74.65333355403185

In [19]:
log_sqft_living = scipy.log(Test['sqft_living'])
log_sqft_living.mean()

7.550274679645938

In [52]:
#model1
X_train = Train[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']]
X_test = Test[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']]

In [53]:
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_train, y_train)

reg.coef_

reg.intercept_

predict =reg.predict(X_test)
TrainPred = reg.predict(X_train)

In [54]:
reg.coef_


array([[ 3.12258646e+02, -5.95865332e+04,  1.57067421e+04,
         6.58619264e+05, -3.09374351e+05]])

In [43]:
# new features

Train['bed_bath_rooms']=Train['bedrooms']*Train['bathrooms']
Test['bed_bath_rooms'] = Test['bedrooms']*Test['bathrooms']

#features for model3
Train['bedrooms_squared'] = Train['bedrooms']**2
Train['log_sqft_living'] = scipy.log(Train['sqft_living'])
Train['lat_plus_long'] = Train['lat']+Train['long']
Test['bedrooms_squared'] = Test['bedrooms']**2
Test['log_sqft_living'] = scipy.log(Test['sqft_living'])
Test['lat_plus_long'] = Test['lat']+Test['long']


In [48]:
#model2
X_train2 = Train[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long','bed_bath_rooms']]
X_test2 = Test[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long','bed_bath_rooms']]


reg2 = LinearRegression().fit(X_train2, y_train)
reg2.score(X_train2, y_train)

reg2.coef_

reg2.intercept_

predict2 =reg2.predict(X_test2)
TrainPred2 = reg2.predict(X_train2)

In [49]:
reg2.coef_

array([[ 3.06610053e+02, -1.13446368e+05, -7.14613083e+04,
         6.54844630e+05, -2.94298969e+05,  2.55796520e+04]])

In [50]:
#model 3
X_train3 = Train[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long','bed_bath_rooms','bedrooms_squared', 'log_sqft_living', 'lat_plus_long']]
X_test3 = Test[['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long','bed_bath_rooms','bedrooms_squared', 'log_sqft_living', 'lat_plus_long']]

# ‘bedrooms_squared’, ‘log_sqft_living’, and ‘lat_plus_long’
reg3 = LinearRegression().fit(X_train3, y_train)
reg3.score(X_train3, y_train)

reg3.coef_

reg3.intercept_

predict3 =reg3.predict(X_test3)
TrainPred3 = reg3.predict(X_train3)

In [55]:
M1Train = sum((y_train - TrainPred)**2)
M2Train = sum((y_train - TrainPred2)**2)
M3Train = sum((y_train - TrainPred3)**2)

print(str(M1Train)+","+ str(M2Train)+","+str(M3Train))

[9.67879963e+14],[9.58419635e+14],[9.03436455e+14]


In [56]:
M1Test = sum((y_test - predict)**2)
M2Test = sum((y_test - predict2)**2)
M3Test = sum((y_test - predict3)**2)

print(str(M1Test)+","+ str(M2Test)+","+str(M3Test))

[2.2550047e+14],[2.23377463e+14],[2.59236319e+14]


In [1]:
280.76*0.092903

26.08344628

In [2]:
y_t

NameError: name 'y_test' is not defined